# Import Numpy

In [1]:
import numpy as np

# Creating NumPy arrays
There are many ways to create arrays in NumPy. 

In [2]:
data = np.array([1, 2, 3, 4, 5])   # Create a rank 1 array

In [3]:
print(data)

[1 2 3 4 5]


In [4]:
ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [5]:
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [12]:
random=np.random.random(5)
print(random)

[0.35411039 0.17741329 0.19986586 0.30916104 0.61254351]


# Array Arithmetic Operations

In [7]:
addition = data + ones 
print(addition)

[2. 3. 4. 5. 6.]


In [8]:
multiplication= data*zeros
print (multiplication)

[0. 0. 0. 0. 0.]


# Indexing & Slicing

In [9]:
i1=data[0]
print(i1)

1


In [13]:
i=2
i2=data[i]
print(i2)

3


In [14]:
slice=data[2:3]  #this slice looks similar to indexed value. But slice is an array whereas index is about values
print(slice)

[3]


In [15]:
slice1=data[0:2]
print(slice1)

[1 2]


In [16]:
slice2=data[1:]
print(slice2)

[2 3 4 5]


In [17]:
slice2=data[:5]
print(slice2)

[1 2 3 4 5]


# Aggregation

In [18]:
print(data.max())
print(data.min())
print(data.sum())

5
1
15


# Exercise

Create an array of length 8. Create two slices - one with first 4 elements and another with last 4 elements. Add the two slices and print the result.

In [25]:
new=np.array([1, 2, 3, 4, 5,6,7,8]) 
new_f=new[:4]
new_b=new[4:]

In [26]:
print(new_f)
print(new_b)

[1 2 3 4]
[5 6 7 8]
