# Import Numpy

In [1]:
import numpy as np

# Creating Matrix: 2-D Array

In [2]:
# Create the following rank 2 array with shape (3, 2)

data = np.array([[1,2], [3,4], [5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
ones=np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
zeros=np.zeros((3,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
random=np.random.random((3,2))
print(random)

[[0.38428546 0.69934737]
 [0.59477233 0.43178696]
 [0.37092566 0.02158296]]


# Matrix Arithmetic Operations

In [7]:
addition = data + ones 
print(addition)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


In [8]:
multiplication= data*zeros
print (multiplication)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Matrix Indexing and Slicing

In [9]:
index1=data[0,1]
print(index1)

2


In [10]:
slice1=data[0:2]
print(slice1)

[[1 2]
 [3 4]]


In [11]:
slice2=data[0:2,0]
print(slice2)

[1 3]


# Matrix Aggregation

In [12]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


# Transposing

In [13]:
dataT=data.T
print(dataT)

[[1 3 5]
 [2 4 6]]


# Reshaping

In [15]:
data_vertical=data.reshape(6,1)
print(data_vertical)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [16]:
data_horizontal=data.reshape(1,6)
print(data_horizontal)

[[1 2 3 4 5 6]]


In [17]:
data_landscape=data.reshape(2,3)
print(data_landscape)

[[1 2 3]
 [4 5 6]]


# Big Matrix

In [18]:
la= np.arange(36) #creates array of numbers from 0 to 36

In [19]:
print(la)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [20]:
bm=la.reshape(6,6)

In [21]:
print(bm)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


# Exercise

In [24]:
slice_o=bm[1:5,1]
print(slice_o)
slice_t=bm[1,1:]
print(slice_t)
slice_th=bm[3:,3:]
print(slice_th)

[ 7 13 19 25]
[ 7  8  9 10 11]
[[21 22 23]
 [27 28 29]
 [33 34 35]]
